# Based on K8s HPA Walkthrough https://v1-20.docs.kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

name: mark-hpa-test

# HPA Settings
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 75

# Initial desired replicas for Deployment / ReplicaSet.
# HPA will manage this after deployment, but we still need an initial value.
# This should always match the HPA minReplicas.
replicaCount: 1

# What resources to assign to our Pods.
# HPA percentages are as a percentage of request.
resources:
  requests:
    cpu: 20m
    memory: 40Mi
  limits:
    cpu: 50m
    memory: 60Mi

image:
  tag: unassigned
  repository: {someimage}.com/training/hpa-test

kotahi:
  catalogueUUID: ANeDPIj_ZP_KyNxFiCGtQq