# Troubleshoot the issues to get the Solution running.
# When working the URL http://<ingress.hosts> should load in your browser.

name: mark-troubleshoot

replicaCount: 1

ingress:
  enabled: true
  hosts:
  - mark-troubleshoot.{someurl}.com

containerPort: 8080

resources:
  requests:
    cpu: 20m
    memory: 30Mi
  limits:
    cpu: 30m
    memory: 40Mi

readiness:
  path: /ping
  initialDelaySeconds: 10
  periodSeconds: 10

image:
  tag: 0.1
  repository: {someUrl}/training/troubleshoot